### ISSUE TITLE
I can add an item without selecting a reminder time

### ISSUE THREAD

**Issue by aberger3647** [the-collab-lab/tcl-67-smart-shopping-list#106]

**Comment by jtkabenni** [comment]
The default value is actually set to 7, but it's just not visually obvious that it's selected right now.

**Comment by aberger3647** [comment]
Edited out Bug. Can we deal with this somehow? Either make it visually obvious, or prevent submitting without selection

**Comment by aberger3647** [comment]
I see that Ricky created an issue for this. I'll close this issue
