### ISSUE TITLE
Add width to Button component

### ISSUE THREAD

**Issue by aberger3647** [the-collab-lab/tcl-67-smart-shopping-list#123]
- Add width prop
- Replace custom buttons with Button component
     - Delete button for list items
     - Add item expand button
     - Log in/log out mobile
     - 7 Day, 14 Day, 30 Day buttons

**Comment by flbarfield** [comment]
So I totally just added the widths on the buttons, as I replaced my signIn/signOut with button components here, and didn't see this issue till after. My bad!

I'll leave you to do the other buttons, though!

https://github.com/the-collab-lab/tcl-67-smart-shopping-list/pull/120
