### ISSUE TITLE
Improve list view and search items bar

### ISSUE THREAD

**Issue by jtkabenni** [the-collab-lab/tcl-67-smart-shopping-list#52]
List view and search bar improvements. 

Todo: 

- [x] Hide search bar if no items in that list.
- [x] Search bar clear input button should be in line with search bar
- [x] Search copy:
- [x] Search your shopping list 
- [x] Search for items in your shopping list 
- [x] Clear instead of just X
- [x] Hitting enter in search bar should not refresh page
- [x] remove: Hello from the /list page!
- [x] Add item form should be above list in list page
- [x] Share list form should be under list in list view, or to bottom right
- [x] Add list name to list view
- [x] 'No items in list, please add items' message when the list view is empty got removed somehow. Please fix

**Comment by aberger3647** [comment]
- Add list name to List view
