### ISSUE TITLE
Improve add item form on manage list page

### ISSUE THREAD

**Issue by jtkabenni** [the-collab-lab/tcl-67-smart-shopping-list#53]
Make updates to add item form on manage list to be more user friendly and descriptive. 

Todo:

- [x] Add label to form, e.g "Add an item to your list"
- [x] Make input label copy more clear
- [x] Consider other option for 'replace in', since we will always only have 3 options, we can consider buttons instead of a dropdown
- [x] Update copy to question form: remind me to replace item in….
- [x] Update button copy

**Comment by flbarfield** [comment]
Working this one async - 3/25
