### ISSUE TITLE
Improve share list form on manage list page

### ISSUE THREAD

**Issue by jtkabenni** [the-collab-lab/tcl-67-smart-shopping-list#54]
Make updates to share list form on manage list to be more user friendly and descriptive. 

Todo:

- [x] Add label to form, e.g "Share list with another user". consider how to make this more clear. what does 'other user' mean? Right now copy says "existing user" which can be confusing.
- [x] Make input label copy more clear
- [x] Update button copy

**Comment by flbarfield** [comment]
On it, 3/26
